"""
GO requires annotation submissions in GAF format, described here: https://geneontology.org/docs/go-annotation-file-gaf-format-2.2/

Has to have a header, which must include the format, and we will include a bit of extra information,
but then it's just a TSV

We will have to ingest some kind of schema that defines the relations, since they depend on the aspect and the term 
being annotated.

"""

import polars as pl
import click
from datetime import datetime


@click.command()
@click.option(
    "--input_parquet",
    type=str,
    help="Path to the input parquet file from GoFlow",
)
@click.option(
    "--output_gaf",
    type=str,
    help="Path to the output GAF file",
)
@click.option("--schema",
    type=str,
    help="Path to the schema file that defines the relations",
)
def main(input_parquet: str, output_gaf: str, schema: str):
    """
    Load the parquet output from GoFlow and convert it to a GAF file 
    """

    go_flow_output = pl.read_parquet(input_parquet).unnest("curation_result").filter(pl.col("annotation").is_not_null())
    id_lookup = pl.read_csv("data/mirna_id_to_urs_lookup.csv").filter(pl.col("rna_id").is_not_null()).unique("rna_id")
    print(id_lookup)
    print(go_flow_output)
    schema_for_conversion = {}

    gaf_data = go_flow_output.join(id_lookup, on="rna_id", how="inner")

    ## Add the columns needed, trim others and rename stuff
    gaf_data = gaf_data.select([
        "PMCID",
        "urs",
        "rna_id",
        "annotation",
        "aes",
    ]).rename({
        "PMCID": "DB:Reference",
        "urs": "DB Object ID",
        "rna_id": "DB Object Symbol",
        "annotation": "GO ID",
    })

    gaf_data = gaf_data.with_columns(
        (pl.lit("RNAcentral").alias("DB")),
        (pl.lit("IEA").alias("Evidence Code")),
        (pl.lit(None).alias("With")),
        (pl.lit(None).alias("DB Object Synonym")),
        (pl.lit("RNAcentral-GOFlowLLM").alias("Assigned By")),
        (pl.lit(f"{datetime.now().strftime('%Y-%m-%d')}").alias("Date")),
    )
    gaf_data = gaf_data.select([
        "DB",
        "DB Object ID",
        "DB Object Symbol",
        # "Relation",
        "GO ID",
        "DB:Reference",
        "Evidence Code",
        "With",
        # "Aspect",
        # "DB Object Name", ## The UniprotKB ID
        "DB Object Synonym", 
        "Assigned By",
        "Date",
    ])
    print(gaf_data)

    ## We open the GAF file and write the header, which should be standard

    header =f"""
!gaf-version: 2.2
!Generated by RNAcentral-GOFlowLLM
!date-generated {datetime.now().strftime("%Y-%m-%d")}"""
    
    # with open(output_gaf, "w") as f:
    #     f.write(header)

    

    print(header)


if __name__ == "__main__":
    main()