apiVersion: v1
kind: Service
metadata:
  name: argilla
  namespace: argilla
spec:
  type: NodePort
  selector:
    app: argilla
  ports:
    - protocol: TCP
      port: 6900
      targetPort: 6900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argilla
  namespace: argilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argilla
  template:
    metadata:
      labels:
        app: argilla
    spec:
      containers:
        - name: argilla
          image: argilla/argilla-server:v2.8.0
          envFrom:
            - configMapRef:
                name: proxy-hh
            - secretRef:
                name: argilla-secret
          ports:
            - containerPort: 6900
