name: Build Docker Image and convert

on:
  push:
    branches: ['main']
    
jobs:
  docker-build:
  runs-on: ubuntu-latest
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - 
      name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
    - 
      name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: /tmp/myimage.tar


  singularity-build:
    runs-on: quay.io/singularity/singularity:v3.8.1
    needs: docker-build
    steps:
      - 
        name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp

      - 
        name: Convert to singularity
        run: |
          singularity build go_flow_llm.sif docker-archive:///tmp/myimage.tar

      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push to ghcr
        run: |
          singularity push go_flow_llm.sif oras://ghcr.io/${github_repository}:latest
